---
- name: Deploy VM from template
  vmware_guest:
    validate_certs: no
    folder: /Unix
    datacenter: "{{ datacenter }}"
    cluster: "{{ cluster }}"
    state: poweredon
    name: "{{ item.host_name }}"
    template: "{{ template }}"
    hardware:
      memory_mb: 4096
      num_cpus: 2
      hotadd_cpu: True
      hotadd_memory: True
    networks:
      - name: "{{ vlan }}"
        ip: "{{ item.ip }}"
        netmask: 255.255.255.0
        gateway: 172.25.35.1
        dns_servers:
          - 172.25.35.192
        start_connected: True
  with_items:
      - { host_name: 'servicenow-1', ip: '172.25.35.191' }
      - { host_name: 'servicenow-2', ip: '172.25.35.194' }
      - { host_name: 'servicenow-3', ip: '172.25.35.195' }
